name: Test & Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_formatting:
    name: 'Check Formatting'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true
      - name: cargo fmt
        run: |
          cargo fmt --all -- --check

  linting:
    name: 'Linting'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - name: cargo clippy
        run: |
          cargo clippy -- --D warnings
